cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:id>/',views.add_cart,name='add_cart'),
    path('remove/<int:id>/',views.remove_cart,name='remove_cart'),
    path('add_single/<int:id>/',views.add_single,name='add_single'),
    path('remove_single/<int:id>/',views.remove_single,name='remove_single'),

]

home/urls.py
from django.urls import path, re_path
from . import views

app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>/',views.all_product,name='category'),
    path('like/<int:id>/',views.product_like,name='product_like'),
    path('unlike/<int:id>/',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>/',views.product_comment,name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('comment_like/<int:id>/',views.comment_like,name='comment_like'),
    # path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('favourite_remove/<int:id>/',views.favourite_remove,name='favourite_remove'),
    path('contact/',views.contact,name='contact'),


]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns=[
    path('<int:id>/',views.order_detail,name='order_detail'),
    path('create/',views.order_create,name='order_create'),
    path('coupon/<int:order_id>',views.coupon_order,name='coupon'),
    path('request/<int:order_id>/<int:price>/',views.send_request,name='request'),
    path('verify/',views.verify,name='verify'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/',include('order.urls', namespace='order')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from home.models import *
from django.forms import ModelForm

class Cart(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants,on_delete=models.CASCADE,null=True,blank=True)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.user.username

class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']

cart/views.py
from django.shortcuts import render,redirect
from home.models import Product
from .models import *
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from order.models import OrderForm

def cart_detail(request):
    cart = Cart.objects.filter(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    user = request.user
    form = OrderForm()
    total = 0
    for p in cart:
        if p.product.status != 'None':
            total += p.variant.total_price * p.quantity
        else:
            total += p.product.total_price * p.quantity

    return render(request,'cart/cart.html',{'category':category,'cart':cart,'nums':nums,'total':total,'form':form,'user':user})

@login_required(login_url='accounts:login')
def add_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    variant = Variants.objects.get(id=id)
    if product.status != 'None':
        var_id = request.POST.get('select')
        data = Cart.objects.filter(user_id=request.user.id, variant_id=var_id)
        if data:
            check= 'yes'
        else:
            check= 'no'
    else:
        data = Cart.objects.filter(user_id=request.user.id, product_id=id)
        if data:
            check= 'yes'
        else:
            check= 'no'
    if request.method == 'POST':
        form = CartForm(request.POST)
        var_id = request.POST.get('select')
        if form.is_valid():
            info = form.cleaned_data['quantity']
            if check == 'yes':
                if product.status != 'None':
                    shop = Cart.objects.get(user_id=request.user.id, product_id=id, variant_id=var_id)
                else:
                    shop = Cart.objects.get(user_id=request.user.id, product_id=id)
                shop.quantity += info
                shop.save()
            else:
                Cart.objects.create(user_id=request.user.id, product_id=id, variant_id=var_id, quantity=info)
        return redirect(url)

@login_required(login_url='accounts:login')
def remove_cart(request,id):
    url = request.META.get('HTTP_REFERER')
    Cart.objects.filter(id=id).delete()
    return redirect(url)

def add_single(request,id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    if cart.product.status == 'None':
        product = Product.objects.get(id=cart.product.id)
        if product.amount > cart.quantity:
            cart.quantity += 1
    else:
        variant = Variants.objects.get(id=cart.variant.id)
        if variant.amount > cart.quantity:
            cart.quantity += 1
    cart.save()
    return redirect(url)

def remove_single(request,id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    if cart.quantity < 2:
        cart.delete()
    else:
        cart.quantity -= 1
        cart.save()
    return redirect(url)



            

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}{% endblock %}

{% block body %}
<div class="container-fluid">
<section>

    <!--Grid row-->
    <div class="row">
        <!--Grid column-->
        <div class="col-lg-7" >
    
            <!-- Card -->
            <div class="mb-3"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); margin: 20px; padding: 30px;">
                <div class="pt-4 wish-list" style="text-align: right;">
        
                    <h5 class="mb-4">تعداد (<span>{{nums}}</span> عدد)</h5>
                    {% for c in cart %}
                    <div class="row mb-4">
                        <div class="col-md-5 col-lg-3 col-xl-3">
                        <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                            <a href="">
                            <img class="img-fluid w-100"
                            src="{{ c.product.image_url }}" alt="Sample">
                            </a>
                        </div>
                        </div>

                    <div class="col-md-7 col-lg-9 col-xl-9" style="background: rgb(250, 249, 248);">
                    <div>
                        <div class="d-flex justify-content-between">
                            <div>
                                <h5>{{ c.product.name }}</h5>
                                <p class="mb-3 text-muted text-uppercase small">ضمانت</p>
                                <p class="mb-2 text-muted text-uppercase small"> رنگ :{{ c.variant.color_variant.name }} </p>
                                <p class="mb-3 text-muted text-uppercase small"> اندازه :{{ c.variant.size_variant.name }}</p>
                            </div>
                        
                            <div>
                                <div class="def-number-input number-input safari_only mb-0 w-100">
                                    <!-- <a href="{% url 'cart:remove_single' c.id %}"><i class="fa fa-minus"></i></a>
                                    <input size="5px" class="quantity" min="0" max="{{c.amount}}" name="quantity" value="{{ c.quantity }}" type="number">                                   
                                    <a href="{% url 'cart:add_single' c.id %}"><i class="fa fa-plus"></i></a> -->
                                    <a href="{% url 'cart:remove_single' c.id %}"><i class="fa fa-minus"></i></a>
            
                                    {{ c.quantity }}
                                    <a href="{% url 'cart:add_single' c.id %}"><i class="fa fa-plus"></i></a>


                                    
                                </div>
                                <!-- <small id="passwordHelpBlock" class="form-text text-muted text-center">(Note, 1 piece)</small> -->
                            </div>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <a href="{% url 'cart:remove_cart' c.id %}" type="button" class="card-link-secondary small text-uppercase mr-3"><i
                                    class="fas fa-trash-alt mr-1"></i> حذف از لیست خرید </a>
                                <a href="{% url 'home:favourite' c.id %}" type="button" class="card-link-secondary small text-uppercase"><i
                                    class="fas fa-heart mr-1"></i> اضافه به علاقه مندی ها </a>
                            </div>
                            <p class="mb-0">
                            <span><strong id="summary">
                            {% if c.product.status != 'None' %}
                                {{ c.variant.total_price | intcomma }} تومان
                            {% else %}
                                {{ c.product.total_price| intcomma }} تومان
                            {% endif %}
                            </strong></span>
                            </p class="mb-0">
                        </div>
                    </div>
                    </div>
                </div>
                <hr class="mb-4">
                {% endfor %}
                
                
                <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i> لطفا پرداخت را هرچه سریعتر انجام دهید, اضافه به لیست خرید به معنای خرید محصول نیست.</p>
        
                </div>
            </div>
        <!-- Card -->
    
        <!-- Card -->
        <!-- <div class="mb-3">
            <div class="pt-4">
    
            <h5 class="mb-4">Expected shipping delivery</h5>
    
            <p class="mb-0"> Thu., 12.03. - Mon., 16.03.</p>
            </div>
        </div> -->
        <!-- Card -->
    
        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4">
    
            <h5 class="mb-4">We accept</h5>
    
            <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa">
            <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express">
            <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard">
            <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
                alt="PayPal acceptance mark">
            </div>
        </div>
        <!-- Card -->
    
        </div>
        <!--Grid column-->
    
        <!--Grid column-->
        <div class="col-lg-5" >
            
        <!-- Card -->
        <div class="mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); margin: 20px; padding: 20px;" dir="rtl" >
            <div class="pt-4">
    
            <h5 class="mb-3" style="text-align: right;">مبلغ نهایی</h5>
    
            <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0" >
                مبلغ اولیه
                <span>{{total}}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                بن خرید
                <span></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                    <strong>قیمت نهایی</strong>
                    <!-- <strong>
                    <p class="mb-0">(including VAT)</p>
                    </strong> -->
                </div>
                <span><strong>{{total}}</strong></span>
                </li>
            </ul>   
            <!-- <a href="{% url 'order:order_create' %}"><button type="button" class="btn btn-primary btn-block">order</button></a> -->
    
            </div>
        </div>
        <!-- Card -->
        <br>
        <hr>
        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4">
    
            <!-- <a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#collapseExample"
                aria-expanded="false" aria-controls="collapseExample">
                Add a discount code (optional)
                <span><i class="fas fa-chevron-down pt-1"></i></span>
            </a> -->
    
            <div class="collapse" id="collapseExample">
                <div class="mt-3">
                <div class="md-form md-outline mb-0">
                    <input type="text" id="discount-code" class="form-control font-weight-light"
                    placeholder="Enter discount code">
                </div>
                </div>
            </div>
            </div>
        </div>
        <!-- Card -->
        <br>
        <hr>
        <!-- Edit address -->

        <div class="mb-3" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); margin: 20px; padding: 20px;text-align: right;">
            <h5 style="text-align: right;">به روز  رسانی اطلاعات</h5>
            <div class="pt-4">
                <form method="POST" action="{% url 'order:order_create' %}">
                {% csrf_token %}
                <div class="card" style="padding: 10px;background-color: #ffffff;">

                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-3 col-form-label">ایمیل</label>
                        <div class="col-sm-9">
                        <input type="email" class="form-control" name="email"  value="{{user.email}}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-3 col-form-label">نام</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="f_name"  value="{{user.first_name}}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-3 col-form-label">نام خانوادگی</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="l_name"  value="{{user.last_name}}">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="" class="col-sm-3 col-form-label">آدرس</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="address"  required>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">ثبت و مرحله بعد</button>
                </div>
                </form>
            </div>
        </div>
        <!-- Edit address -->
    
        </div>
        <!--Grid column-->
    </div>
    </div>
    <!-- Grid row -->
       
    </section>
    </div>
          
{% endblock body %}