cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:id>/',views.add_cart,name='add_cart'),
    path('remove/<int:id>/',views.remove_cart,name='remove_cart'),
    path('add_single/<int:id>/',views.add_single,name='add_single'),
    path('remove_single/<int:id>/',views.remove_single,name='remove_single'),

]

home/urls.py
from django.urls import path, re_path
from . import views

app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>/',views.all_product,name='category'),
    path('like/<int:id>/',views.product_like,name='product_like'),
    path('unlike/<int:id>/',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>/',views.product_comment,name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('comment_like/<int:id>/',views.comment_like,name='comment_like'),
    # path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('favourite_remove/<int:id>/',views.favourite_remove,name='favourite_remove'),
    path('contact/',views.contact,name='contact'),


]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/',include('order.urls', namespace='order')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.forms import ModelForm
from django.db.models import Avg
from django_jalali.db import models as jmodels

class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True,related_name='sub')
    sub_cat = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True,unique=True,null=True,blank=True)
    image = models.ImageField(upload_to='category/',null=True,blank=True)

    def __str__(self):
        return self.name
    
    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    
    def get_absolute_url(self):
        return reverse('home:category',args=[self.slug,self.id])

class Product(models.Model):
    VARIANT = (
        ('None','none'),
        ('Size','size'),
        ('Color','color'),
        ('Both','Both'),
    )
    category = models.ManyToManyField(Category,blank=True,related_name='cat_product')
    name = models.CharField(max_length=200)
    amount = models.PositiveIntegerField()
    unit_price = models.PositiveIntegerField()
    change = models.BooleanField(default=True)
    discount = models.PositiveIntegerField(blank=True,null=True)
    total_price = models.PositiveIntegerField()
    information = RichTextUploadingField(blank=True,null=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    available = models.BooleanField(default=True)
    status = models.CharField(null=True,blank=True,max_length=200,choices=VARIANT)
    color = models.ManyToManyField('Color',blank=True)
    size = models.ManyToManyField('Size',blank=True)
    brand = models.ForeignKey('Brand',on_delete=models.CASCADE,blank=True,null=True)
    image = models.ImageField(upload_to='product/',blank=True,null=True)
    like = models.ManyToManyField(User, blank=True, related_name='product_like')
    total_like = models.IntegerField(default=0)
    unlike = models.ManyToManyField(User, blank=True, related_name='product_unlike')
    total_unlike = models.IntegerField(default=0)
    favourite = models.ManyToManyField(User,blank=True,related_name='fa_user')
    total_favourite = models.IntegerField(default=0)
    sell = models.IntegerField(default=0)

    def average(self):
        data = Comment.objects.filter(is_reply=False,product=self).aggregate(avg=Avg('rate'))
        star = 0
        if data['avg'] is not None:
            star = round(data['avg'],1)
        return star


    def total_like(self):
        return self.like.count()

    def total_unlike(self):
        return self.unlike.count()

    def __str__(self):
        return self.name
    
    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    @property
    def total_price(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.discount * self.unit_price)/100
            return int(self.unit_price - total)
        self.total_price

class Size(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Variants(models.Model):
    name = models.CharField(max_length=100)
    update = jmodels.jDateTimeField(auto_now=True)
    product_variant = models.ForeignKey(Product,on_delete=models.CASCADE,related_name='pr')
    size_variant = models.ForeignKey(Size,on_delete=models.CASCADE,blank=True,null=True)
    color_variant = models.ForeignKey(Color,on_delete=models.CASCADE,blank=True,null=True)
    amount = models.PositiveIntegerField()
    unit_price = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True,null=True)
    total_price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.discount * self.unit_price)/100
            return int(self.unit_price - total)
        self.total_price

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    comment = models.TextField()
    rate = models.PositiveIntegerField(default=1)
    create = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True,related_name='comment_reply')
    is_reply = models.BooleanField(default=False)
    comment_like = models.ManyToManyField(User,blank=True,related_name='com_like')
    total_comment_like = models.PositiveIntegerField(default=0)

    def total_comment_like(self):
        return self.comment_like.count()

    def __str__(self):
        return self.product.name

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment','rate']

class ReplyForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class Images(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    name = models.CharField(max_length=100,blank=True)
    image = models.ImageField(upload_to='image/',blank=True,null=True)

    def __str__(self):
        return self.name
        
    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

class Brand(models.Model):
    name = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.name

class Gallery(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    image = models.ImageField(upload_to='gallery/',blank=True,null=True)

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

home/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib import messages
from .forms import *
from django.db.models import Q,Max,Min,Count,Sum
from cart.models import *
from cart.views import *
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from .filters import ProductFilter
from urllib.parse import urlencode


def home(request):
    products = Product.objects.all()
    category = Category.objects.filter(sub_cat=False)
    gallery = Gallery.objects.all()
    create = Product.objects.all().order_by('-create')[:6]
    data = 'pants'
    create2 = products.filter(Q(name__icontains=data))
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    return render(request,'home/home.html',{'category':category,'gallery':gallery,'create':create,'create2':create2,'nums':nums})

def all_product(request,slug=None,id=None):
    products = Product.objects.all()
    # form = CompareForm()
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    min = Product.objects.aggregate(unit_price=Min('unit_price'))
    min_price = int(min['unit_price'])
    max = Product.objects.aggregate(unit_price=Max('unit_price'))
    max_price = int(max['unit_price'])

    filter = ProductFilter(request.GET,queryset=products)
    products = filter.qs
    
    paginator = Paginator(products,12)
    page_num = request.GET.get('page')
    data = request.GET.copy()
    if 'page' in data:
        del data['page']

    page_obj = paginator.get_page(page_num)
    category = Category.objects.filter(sub_cat=False)
    if slug and id:
        data = get_object_or_404(Category,slug=slug,id=id)
        page_obj = products.filter(category=data)
        paginator = Paginator(page_obj,6)
        page_num = request.GET.get('page')
        data = request.GET.copy()
        if 'page' in data:
            del data['page']
        page_obj = paginator.get_page(page_num)
    s_form = SearchForm()
    if 'search' in request.GET:
        s_form = SearchForm(request.GET)
        if s_form.is_valid():
            info = s_form.cleaned_data['search']
            page_obj = products.filter(Q(name__icontains=info))
            paginator = Paginator(page_obj, 6)
            page_num = request.GET.get('page')
            data = request.GET.copy()
            if 'page' in data:
                del data['page']
            page_obj = paginator.get_page(page_num)
    return render(request,'home/product.html',{'products':page_obj,'category':category,'nums':nums,'s_form':s_form,'page_num':page_num,'filter':filter,'min_price':min_price,'max_price':max_price,'data':urlencode(data)})

def product_detail(request,id):
    product = get_object_or_404(Product,id=id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    images = Images.objects.filter(product_id=id)
    create = Product.objects.all().order_by('-create')[:6]
    comment_form = CommentForm()
    reply_form = ReplyForm()
    cart_form = CartForm()
    comments = Comment.objects.filter(product_id=id,is_reply=False)
    similar = product.tags.similar_objects()[:6]
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        is_like = True

    is_unlike = False
    if product.unlike.filter(id=request.user.id).exists():
        is_unlike = True

    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        is_favourite = True


    if product.status != 'None':
        if request.method == 'POST':
            variant = Variants.objects.filter(product_variant_id=id)
            var_id = request.POST.get('select')
            variants = Variants.objects.get(id=var_id)
            colors = Variants.objects.filter(product_variant_id=id,size_variant_id=variants.size_variant_id)
            size = Variants.objects.raw('SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id', [id])

        else:
            variant = Variants.objects.filter(product_variant_id=id)
            variants = Variants.objects.get(id=variant[0].id)
            colors = Variants.objects.filter(product_variant_id=id,size_variant_id=variants.size_variant_id)
            size = Variants.objects.raw('SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id', [id])

            
        context = {'product':product,'category':category,'nums':nums,'variant':variant,'variants':variants,'similar':similar, 'is_like':is_like, 'is_unlike':is_unlike,'comments':comments,'comment_form':comment_form,'reply_form':reply_form,'images':images,'cart_form':cart_form,'is_favourite':is_favourite,'colors':colors,'size':size,'create':create}
        return render(request, 'home/detail.html',context)
    else:
        return render(request,'home/detail.html',{'product':product,'nums':nums,'similar':similar, 'is_like':is_like,'is_unlike':is_unlike,'comments':comments,'comment_form':comment_form,'reply_form':reply_form,'images':images,'cart_form':cart_form,'is_favourite':is_favourite,'create':create})

def product_like(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
        is_like = False
        messages.success(request,'remove','success')
    else:
        product.like.add(request.user)
        is_like = True
        messages.success(request,'add','success')
    return redirect(url)

def product_unlike(request,id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product,id=id)
    product.unlike.add(request.user)
    messages.success(request,'add like','dark')
    return redirect(url)

def product_comment(request,id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            data = comment_form.cleaned_data
            Comment.objects.create(comment=data['comment'],rate=data['rate'],user_id=request.user.id,product_id =id)
            return redirect(url)


def product_reply(request,id,comment_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        reply_form = ReplyForm(request.POST)
        if reply_form.is_valid():
            data = reply_form.cleaned_data
            Comment.objects.create(comment=data['comment'],user_id=request.user.id,product_id =id,reply_id=comment_id,is_reply=True)
            messages.success(request,'tnx for reply','primary')
            return redirect(url)

def comment_like(request,id):
    url = request.META.get('HTTP_REFERER')
    comment = Comment.objects.get(id=id)
    if comment.comment_like.filter(id=request.user.id).exists():
        comment.comment_like.remove(request.user)
    else:
        comment.comment_like.add(request.user)
        messages.success(request,'tnx for like comment','warning')
    return redirect(url)

# def product_search(request):
#     products = Product.objects.all()
#     if request.method == 'POST':
#         form = SearchForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data['search']
#             if data.is_digit():
#                 products = products.filter(Q(discount__exact=data)|Q(unit_price__exact=data))
#             else:
#                 products = products.filter(Q(name__contains=data))
#             return render(request,'home/product.html',{'products':products,'form':form})

def favourite_product(request,id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        product.favourite.remove(request.user)
        product.total_favourite -= 1
        product.save()
        is_favourite = False
    else:
        product.favourite.add(request.user)
        product.total_favourite += 1
        product.save()
        is_favourite = True

    return redirect(url)

def favourite_remove(request,id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    product.favourite.remove(request.user)
    return redirect(url)

def contact(request):
    # if request.method == 'POST':
    #     subject = request.POST['subject']
    #     email = request.POST['email']
    #     msg = request.POST['message']
    #     body = subject + '\n' + email + '\n' + msg
    #     form = EmailMessage(
    #         'contact form',
    #         body,
    #         'test',
    #         ('villolin68@gmail.com',),
    #     )
    #     form.send(fail_silently=False)
    return render(request,'home/contact.html')

home/templates/home/contact.html
{% extends 'base.html' %}
{% block body%}
<div class="container">
    <div class="card bg-dark mt-5 p-5">
        <form method="post" action="{% url 'home:contact' %}"> 
            {% csrf_token %}
            <h1 class="text-center" style="color: goldenrod">Contact Form</h1>

            <div class="row mt-3">
                <div class="col-6">
                    <input type="text" name="subject" class="form-control" placeholder="subject">
                </div>

                <div class="col-6">
                    <input type="email" name="email" class="form-control" placeholder="email">
                </div>
            </div>

            <div class="row mt-3">
                <textarea name="message" class="form-control" placeholder="message" rows="4"></textarea>
            </div>
            <br>
            <button type="submit" class="btn btn-danger mt-3">send email</button>
        </form>

    </div>

</div>
{% endblock body%}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}

{% block title%}  {% endblock title%} 

{% block body%}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <!-- gallery is folder for pic of carousel  -->
  <div class="carousel-inner">
    {% for i in gallery %}
      <div class="carousel-item {% if forloop.first %} active {% endif %}">
        <img src="{{i.image.url}}"  class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5></h5>
        </div>
      </div>
    {% endfor %}
  </div>
   
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>

<div class="container-fluid" dir="rtl">
  <h3 style="text-align: right;">جدیدترین محصولات</h3>
  <hr>
<!-- Swiper1 -->
  <div class="swiper-container slider1" >

    <div class="swiper-wrapper" >
      {% for i in create %}
        <div class="swiper-slide"   >
          <div class="card" style="width: 23rem;text-align: center;">
            <img src="{{i.image_url}}" style="height: 250px;width: 250px;" class="card-img-top" alt="..." style="text-align: center;">
            <div class="card-body">
              <h5 class="card-title">{{ i.name }}</h5>
              <a href="{% url 'home:detail' i.id %}" class="btn btn-primary">مشاهده جزئیات محصول</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <!-- Add Pagination -->
    <br>
    <br>
    <div class="swiper-pagination">
    </div>

  </div>
</div>
<!-- <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script> -->

<hr>
 
<!-- Swiper2 -->
<div class="container-fluid">
  <h3 style="text-align: right;">شلوارهای زنانه</h3>
  <hr>
  <div class="swiper-container slider2">
    <div class="swiper-wrapper">    
      {% for j in create2 %}
        <div class="swiper-slide">
          <div class="card" style="width: 23rem;text-align: center;">
            <img src="{{j.image_url}}" style="height: 250px;width: 250px;" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{ j.name }}</h5>
              <a href="{% url 'home:detail' j.id %}" class="btn btn-primary">مشاهده جزئیات محصول</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <!-- Add Pagination -->
    <br>
    <br>
    <div class="swiper-pagination">
    </div>
  </div>
</div>

<hr>

  <div class="container">
    <a href="{% url 'home:product' %}">
      <button type="button" class="btn btn-outline-primary" data-mdb-ripple-color="dark" style="width: 400px; height: 70px;">مشاهده همه محصولات</button>
    </a>
  </div>

<hr>

 <!-- Swiper JS -->
 <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

 
 
{% endblock body%}

home/templates/home/t2.html
<div class="container">
    <div class="row">
        <div class="col-10">
            <h1>{{product.name}}</h1>
            <h4>rate:{{product.average}}</h4><br>
            <img style="width: 250px" src="{{product.image_url}}" alt=""><br>
            <p>{{product.information|safe}}</p>


            {% for img in images %}
                <img src="{{ img.image.url }}" style="width: 250px;height: 200px;" alt="">
            {% endfor %}

            {% if is_favourite %}
                <a href="{% url 'home:favourite' product.id %}"><i class="fas fa-heart" style="color:red; font-size: 24px "></i></a>
            {% else %}
                <a href="{% url 'home:favourite' product.id %}"><i class="far fa-heart" style="font-size: 24px "></i></a>
            {% endif %}
        </div>

        <div class="col-2 mt-3">
            <div class="row">
                <h3>like: {{product.total_like}}</h3>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'home:product_like' product.id %}" class="btn btn-info {% if is_unlike %} disabled {% endif %}">like</a><br><br>

                    <h3>unlike: {{product.total_unlike}}</h3>
                    <a href="{% url 'home:product_unlike' product.id %}" class="btn btn-primary {% if is_like %} disabled {% endif %}">dislike</a><br><br>
                {% endif %}
            </div>
        </div>


{% if product.status == 'Size' %}
    <form action="" method="POST">
        {% csrf_token %}
        {% for data in variant %}
            <input type="radio" value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} name="select" onchange="this.form.submit();">
            <a href="" style="text-decoration: none;">{{data.size_variant}}</a>
        {% endfor %}
    </form>
{% elif product.status == 'Color' %}
    <form action="" method="POST">
        {% csrf_token %}
        {% for data in variant %}
            <input type="radio" value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} name="select" onchange="this.form.submit();">
            <a href="" style="text-decoration: none;">{{data.color_variant}}</a>
        {% endfor %}
    </form>

{% endif %}
<hr>
<!-- {% for tag in similar%}
    <a href="{% url 'home:detail' tag.id %}">
        <img style="width: 200px;height: 200px" src="{{tag.image.url}}}" alt="">
    </a>
{% endfor %} -->
<div class="card bg-danger m-2">
    <h4>your choice price: {{variants.total_price}}</h4>
</div>
<div class="card">
    {% if product.status != 'None' %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ cart_form }}
        <button type="submit">Add</button>
    </form>
    {% else %}
    <form method="POST" action="{% url 'cart:add_cart' product.id %}">
        {% csrf_token %}
        <input type="number" name="quantity" min="1" value="1" max="{{ product.amount }}" required oninvalid="setCustomValidity(باید تعداد حداکثر {{ product.amount }} باشد)">
        <button type="submit">Add</button>
    </form>
    {% endif %}
</div>
<hr>

<div class="row comment">
    <div class="col-8">
        {% if user.is_authenticated %}
            <form method="POST" action="{% url 'home:product_comment' product.id %}">
                {% csrf_token %}
                <div class="card">
                    <div class="row">
                        <div class="col-12">
                            <div class="comment-box">
                                <h4>Add Comment</h4>
                                <div class="rating">
                                    <input type="radio" name="rate" value="5" id="5"><label for="5">&star;</label>
                                    <input type="radio" name="rate" value="4" id="4"><label for="4">&star;</label>
                                    <input type="radio" name="rate" value="3" id="3"><label for="3">&star;</label>
                                    <input type="radio" name="rate" value="2" id="2"><label for="2">&star;</label>
                                    <input type="radio" name="rate" value="1" id="1"><label for="1">&star;</label>
                                </div>
                                <div class="comment-area">
                                    <textarea name="comment" placeholder="comment ..." class="form-control" id="comment" rows="4" required oninvalid="setCustomValidity('لطفا نظر خود را درج کنید.')"></textarea>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-danger m-2">Send Comment</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        {% endif %}
       
    </div>
</div>

{% for com in comment %}
    <div class="card bg-dark text-white mb-2">
        <div class="row">
            <div class="col-8">
                <p>{{ com.user.username }}</p>
            </div>
            <div class="col-4">
                <div class="comment-rating">
                    <i class="fa fa-star{% if com.rate < 1 %}-o empty {% endif %}"></i>   
                    <i class="fa fa-star{% if com.rate < 2 %}-o empty {% endif %}"></i>   
                    <i class="fa fa-star{% if com.rate < 3 %}-o empty {% endif %}"></i>   
                    <i class="fa fa-star{% if com.rate < 4 %}-o empty {% endif %}"></i>   
                    <i class="fa fa-star{% if com.rate < 5 %}-o empty {% endif %}"></i> 
                </div>  
            </div>
        </div>
        <div class="row p-3">
            <p>{{ com.comment }}</p>
        </div>

        <div class="row">
            <div class="p-2 m-2">
                {% if user.is_authenticated %}
                    <a href="{% url 'home:comment_like' com.id %}" class="like m-2 cursor">
                        <i class="fa fa-thumbs-o-up"></i>
                        <span>Like</span>&nbsp; {{com.total_like_comment}}
                    </a>
                {% endif %}
            </div>
        </div>


    </div>
    {% for com in comment %}
    <p>{{ com.comment }}</p><br>
    <small>{{ com.rate }}</small>
    {% endfor %}
<hr>
<form method="POST" action="{% url 'home:product_reply' product.id com.id %}">
    {% csrf_token %}
    <textarea name="comment" id="comment" placeholder="reply ..." class="form-control" rows="4"></textarea>
    <div class="mt-2">
        <button type="submit" class="btn btn-info">Send Reply</button>
    </div>
</form>
{% for data in com.comment_reply.all %}
    <p>{{ data.comment }}</p>
{% endfor %}
{% endfor %}

</div>