accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.user_register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.user_profile,name='profile'),
    path('update/',views.user_update,name='update'),
    path('change/',views.change_password,name='change'),
    path('login_phone/',views.phone,name='phone'),
    path('verify/',views.verify,name='verify'),
    path('favourite/',views.favourite,name='favourite'),
    path('history/',views.history,name='history'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:id>/',views.add_cart,name='add_cart'),
    path('remove/<int:id>/',views.remove_cart,name='remove_cart'),
    path('add_single/<int:id>/',views.add_single,name='add_single'),
    path('remove_single/<int:id>/',views.remove_single,name='remove_single'),

]

home/urls.py
from django.urls import path, re_path
from . import views

app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>/',views.all_product,name='category'),
    path('like/<int:id>/',views.product_like,name='product_like'),
    path('unlike/<int:id>/',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>/',views.product_comment,name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('comment_like/<int:id>/',views.comment_like,name='comment_like'),
    # path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('favourite_remove/<int:id>/',views.favourite_remove,name='favourite_remove'),
    path('contact/',views.contact,name='contact'),


]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/',include('order.urls', namespace='order')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from phone_field import PhoneField

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=300,null=True, blank=True)
    profile_image = models.ImageField(upload_to='profile/',default='../media/profile/1.jpg',null=True,blank=True)

    def __str__(self):
        return self.user.username

    @property
    def profile_image_url(self):
        if self.profile_image and hasattr(self.profile_image, 'url'):
            return self.profile_image.url


# signals
def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()

post_save.connect(save_profile_user, sender=User)

accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

error ={
    'min_length':'حداقل باید 5 کاراکتر باشد',
    'required':'این فیلد اجباری است',
    'invalid':'ایمیل شما نامعتبر است',
}

class UserRegisterForm(forms.Form):
    user_name = forms.CharField(max_length=50,error_messages=error,widget=forms.TextInput(attrs={'placeholder':'نام کاربری ...', 'class':'form-control'}),label=False)
    email = forms.EmailField(error_messages=error,widget=forms.EmailInput(attrs={'placeholder':' ایمیل ...','class':'form-control'}),label=False)
    first_name = forms.CharField(max_length=50,min_length=5,error_messages=error,widget=forms.TextInput(attrs={'placeholder':' نام ...','class':'form-control'}),label=False)
    last_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder':' نام خانوادگی ...','class':'form-control'}),label=False)
    password_1 = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'placeholder':' رمز ورود ...','class':'form-control'}),label=False)
    password_2 = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'placeholder':' تکرار رمز ورود ...','class':'form-control'}),label=False)

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError('نام کاربری موجود است')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('ایمبل موجود است')
        return email

    def clean_password_2(self):
        password1 = self.cleaned_data['password_1']
        password2 = self.cleaned_data['password_2']
        if password1 != password2:
            raise forms.ValidationError('رمز عبور با تکرار رمز یکسان نیست')
        elif len(password2) < 5:
            raise forms.ValidationError('پسورد کوتاه است')
        elif not any(x.isupper() for x in password2):
            raise forms.ValidationError('پسورد حداقل باید یک حرف بزرگ داشته باشد.')
        return password1

class UserLoginForm(forms.Form):
    user = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'input username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'input password'}))
    remember = forms.BooleanField(required=False,widget=forms.CheckboxInput())

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','first_name','last_name']
        labels = {
        "email": "ایمیل","first_name": "نام","last_name": "نام خانوادگی"
    }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone','address','profile_image']
        labels = {
        "phone": "تلفن","address": "آدرس","profile_image": "عکس کاربر"
    }

class PhoneForm(forms.Form):
    phone = forms.IntegerField()

class CodeForm(forms.Form):
    code = forms.IntegerField()

accounts/views.py
from django.shortcuts import render,redirect
from .forms import *
from .models import *
from order.models import *
from home.models import *
from cart.models import *
from django.db.models import Sum
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from random import randint
import ghasedakpack
from django.http import HttpResponse 

def user_register(request):
    category = Category.objects.filter(sub_cat=False)
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'],email=data['email'],first_name=data['first_name'],last_name=data['last_name'],password=data['password_1'])
            user.save()

            return redirect('home:home')

            messages.success(request,'حساب کاربری با موفقیت ساخته شد','success')
            
    else:
        form = UserRegisterForm()
    context = {'form':form,'category':category}
    return render(request, 'accounts/register.html', context)

def user_login(request):
    url = request.META.get('HTTP_REFERER')
    category = Category.objects.filter(sub_cat=False)
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            remember = data['remember']
            try:
                user = authenticate(request, username=User.objects.get(email=data['user']), password=data['password'])
            except:
                user = authenticate(request, username=data['user'], password=data['password'])

            if user is not None:
                login(request,user)
                if not remember:
                    request.session.set_expiry(0)
                else:
                    request.session.set_expiry(10000)
                # messages.success(request,'welcome my site','primary')
                return redirect('home:home')  
            else:
                print ( "invalid login details ")
                return redirect(url)
    else:
        form = UserLoginForm()
    context ={'form':form,'category':category}
    return render(request, 'accounts/login.html', context)
    

def user_logout(request):
    # url = request.META.get('HTTP_REFERER')
    logout(request)
    return redirect('home:home')


@login_required(login_url='accounts:login')
def user_profile(request):
    profile = Profile.objects.get(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    products = Product.objects.all()
    create = Product.objects.all().order_by('-create')[:6]
    context = {'category':category,'profile':profile,'nums':nums,'create':create}
    return render(request,'accounts/profile.html',context)

@login_required(login_url='accounts:login')
def user_update(request):
    profile = Profile.objects.get(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST,instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if user_form and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'update successfully','success')
            return redirect('accounts:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {'user_form':user_form,'profile_form':profile_form,'category':category,'profile':profile,'nums':nums}
    return render(request,'accounts/update.html',context)


def change_password(request):
    profile = Profile.objects.get(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    if request.method == 'POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success(request,'passwor successfully changed','success')
            return redirect('accounts:profile')
        else:
            messages.error(request,'password not correct','danger')
            return redirect('accounts:change')
    else:
        form = PasswordChangeForm(request.user)

    return render(request,'accounts/change.html',{'form':form,'category':category,'profile':profile,'nums':nums})

def phone(request):
    if request.method == 'POST':
        form = PhoneForm(request.POST)
        if form.is_valid():
            global random_code,phone
            data = form.cleaned_data
            phone = f"0{data['phone']}"
            random_code = randint(100,1000)
            sms = ghasedakpack.Ghasedak("3f269a0a1b77f8f09813f2476e8105367d612c824154b3acc221030ae5ef05f9")
            sms.send({'message':random_code,'receptor':phone,'linenumber':"10008566"})
            return redirect('accounts:verify')
    else:
        form = PhoneForm()
    return render(request,'phone.html',{'form':form})

def verify(request):
    if request.method == 'POST':
        form = CodeForm(request.POST)
        if form.is_valid():
            if random_code == form.cleaned_data['code']:
                profile = Profile.objects.get(phone=phone)
                user = User.objects.get(profile__id=profile.id)
                login(request,user)
                messages.success(request,'hi user')
                return redirect('home:home')
            else:
                messages.error(request,'error code')
    else:
        form = CodeForm()
    return render(request,'accounts/code.html',{'form':form})

def favourite(request):
    profile = Profile.objects.get(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    product = request.user.fa_user.all()
    return render(request,'accounts/favourite.html',{'product':product,'category':category,'profile':profile,'nums':nums})

def history(request):
    profile = Profile.objects.get(user_id=request.user.id)
    category = Category.objects.filter(sub_cat=False)
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    data = ItemOrder.objects.filter(user_id = request.user.id)
    return render(request,'accounts/history.html',{'data':data,'category':category,'profile':profile,'nums':nums})

accounts/templates/accounts/change.html
{% extends 'base.html'%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/dashbord.css' %}">
{% endblock css %}
{% block title%} {% endblock title%} 

{% block body%}
   <div class="container-fluid">
       <div class="row" style="text-align: right;">

        <div class="col-2">
            <div class="side-menu" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding: 10px;margin: 10px;border: 5px;">
                <div class="image-container">
                    <a href="{% url 'accounts:profile' %}">
                    <img src="{{user.profile.profile_image_url}}"  alt="" >
                    </a>
                </div>
                <h4 style="text-align: center;">&nbsp;{{profile.user.username}}</h4>
                <hr>
                <a href="{% url 'accounts:update' %}"><i class="fa fa-edit" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;بروزرسانی </a>
                <a href="{% url 'accounts:change' %}"><i class="fa fa-key" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تغییر رمز عبور</a>
                <a href="{% url 'accounts:history' %}"><i class="fa fa-history" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تاریخچه</a>
                <a href="{% url 'accounts:favourite' %}"><i class="fa fa-heart" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;علاقه مندی ها</a>
             </div>
        </div>

        <div class="col-8">
            <div class="profile">
                <div class="card-body">    
                    <h6 class="card-subtitle mb-2 text-muted">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-info btn-md" style="width: 300px;">change</button>
                    
                        </form>
                    </h6>                    
                </div>
            </div>
        </div>

        </div>
    </div>
           
{% endblock body%}


<style>
    form ul {
        display: none;
    }
</style>

accounts/templates/accounts/code.html
{% extends 'base.html'%}
{%block title %} {%endblock title %}

{%block body %} 
<h1>phone login<h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">login</button>
    </form>

{%endblock body %}

accounts/templates/accounts/favourite.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/dashbord.css' %}">
{% endblock css %}
{% block title%} {% endblock title%} 

{% block body%}
   <div class="container-fluid">
        <div class="row" style="text-align: right;">

            <div class="col-2">
                <div class="side-menu" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding: 10px;margin: 10px;border: 5px;">
                    <div class="image-container">
                        <a href="{% url 'accounts:profile' %}">
                        <img src="{{user.profile.profile_image_url}}"  alt="" >
                        </a>
                    </div>
                    <h4 style="text-align: center;">&nbsp;{{profile.user.username}}</h4>
                    <hr>
                    <a href="{% url 'accounts:update' %}"><i class="fa fa-edit" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;بروزرسانی </a>
                    <a href="{% url 'accounts:change' %}"><i class="fa fa-key" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تغییر رمز عبور</a>
                    <a href="{% url 'accounts:history' %}"><i class="fa fa-history" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تاریخچه</a>
                    <a href="{% url 'accounts:favourite' %}"><i class="fa fa-heart" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;علاقه مندی ها</a>
                 </div>
            </div>

           <div class="col-8">
               <div class="profile" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); margin: 20px; padding: 30px;">
                    {% for i in product %}
                        {% if i.favourite %}
                            <div class="row mb-4">
                                <div class="col-md-5 col-lg-3 col-xl-3">
                                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                                    <a href="{% url 'home:detail' i.id %}">
                                    <img class="img-fluid w-50"
                                    src="{{ i.image_url }}" alt="Sample" style="width: 80px;height: 70px;">
                                    </a>
                                </div>
                                </div>
        
                                <div class="col-md-7 col-lg-9 col-xl-9" style="background: rgb(250, 249, 248);">    
                                    <div class="d-flex justify-content-between">
                                        
                                        <h5>{{ i.name }}</h5>                                       
                                        <p class="mb-2 text-muted text-uppercase small">{{ i.variant.color_variant.name }} رنگ :</p>
                                        <p class="mb-3 text-muted text-uppercase small">{{ i.variant.size_variant.name }} اندازه :</p>
                                        <p class="mb-3 text-muted text-uppercase small">  قیمت :{{ i.unit_price }} تومان</p>
                                        <a href="{% url 'home:favourite_remove' i.id %}" type="button" class="card-link-secondary small text-uppercase mr-3"><i
                                            class="fas fa-trash-alt mr-1"></i> حذف </a>
                                        
                                    </div>                                    
                                </div>

                            </div>
                            <hr>                   
                            <!-- <a href="{% url 'home:detail' i.id %}"><img src="{{i.image.url}}" style="width: 100px;height: 100px;" alt="">{{ i.name }}</a> -->
                        {% else %}
                        
                            <img src='../media/profile/likes-folder(1).png'>
                            <p>not favourite exist</p>
                        
                        {% endif %}
                    {% endfor %}
            </div>
        </div>
   </div>
</div>

           
{% endblock body%}

accounts/templates/accounts/history.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/dashbord.css' %}">
{% endblock css %}
{% block title%} {{ profile.user.username }} {% endblock title%} 

{% block body%}
<div class="container-fluid">
    <div class="row" style="text-align: right;">

        <div class="col-2">
            <div class="side-menu" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding: 10px;margin: 10px;border: 5px;">
                <div class="image-container">
                    <a href="{% url 'accounts:profile' %}">
                    <img src="{{user.profile.profile_image_url}}"  alt="" >
                    </a>
                </div>
                <h4 style="text-align: center;">&nbsp;{{profile.user.username}}</h4>
                <hr>
                <a href="{% url 'accounts:update' %}"><i class="fa fa-edit" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;بروزرسانی </a>
                <a href="{% url 'accounts:change' %}"><i class="fa fa-key" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تغییر رمز عبور</a>
                <a href="{% url 'accounts:history' %}"><i class="fa fa-history" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تاریخچه</a>
                <a href="{% url 'accounts:favourite' %}"><i class="fa fa-heart" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;علاقه مندی ها</a>
             </div>
        </div>

        <div class="col-8">
            <div class="profile">

                <table class="table table-striped">
                    <thead style="text-align: right;">
                        <tr>
                        <th scope="col"></th>
                        <th scope="col" style="width:150px;">عکس محصول</th>
                        <th scope="col" style="width:200px;">نام محصول</th>
                        <th scope="col">سایز</th>
                        <th scope="col">رنگ</th>
                        <!-- <th scope="col">price</th>                                             -->
                        <th scope="col" style="width:150px;">قیمت نهایی</th>
                        <th scope="col" style="width:200px;">آدرس</th>
                        <th scope="col" style="width:200px;">وضعیت پرداخت</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in data %}
                            <tr style="text-align: right;">
                                <th scope="row">{{ forloop.counter }}</th>
                                <td style="width:150px;text-align: right;"><img src="{{i.product.image_url}}" style="width: 50px;height: 50px;" alt=""></td>
                                <td style="text-align: right;">{{ i.product.name }}</td>
                                <td style="text-align: right;">{{ i.variant.size_variant.name }}</td>
                                <td style="text-align: right;">{{ i.variant.color_variant.name }}</td>
                                <!-- <td>
                                    {% if i.product.status != 'None' %}
                                        {{ i.variant.total_price }}
                                    {% else %}
                                        {{ i.product.total_price }}
                                    {% endif %}
                                </td> -->
                                <td style="text-align: right;">
                                    {% if i.product.status != 'None' %}
                                        {% widthratio i.variant.total_price 1 i.quantity %}
                                    {% else %}
                                        {% widthratio i.product.total_price 1 i.quantity %}
                                    {% endif %}
                                </td>
                                <td style="text-align: right;">{{ i.order.address }}</td>
                                <td style="text-align: right;">
                                    {% if i.order.paid == True %}
                                    <p>پرداخت شد</p>
                                    {% else %}
                                    <p>پرداخت نشد</p>
                                    {% endif %}
                                </td>
                                
                            </tr>
                        {% endfor %}
        
                    </tbody>
                </table>


                <!-- <div class="card mt-3 p-5">
                    {% for i in data %}
                        <h2>name :{{ i.product.name }} &nbsp; price: {{i.order.get_price}}</h2>
                        <img src="{{i.product.image_url}}" style="width: 200px;height: 200px;" alt="">
                        <h3>address: {{ i.order.address }}</h3>
                        {% if i.order.paid == True %}
                        <p>پرداخت شد.</p>
                        {% else %}
                        <p>پرداخت نشد.</p>
                        {% endif %}
            
                        <hr>
                    {% endfor %}
                </div> -->
                    
            </div>
        </div>

    </div>
</div>
           
{% endblock body%}

accounts/templates/accounts/phone.html
{% extends 'base.html'%}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/dashbord.css'%}">
{% endblock css %}
{%block title %} {%endblock title %}

{%block body %} 
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send code</button>
    </form>


{%endblock body %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'accounts/css/dashbord.css'%}">
{% endblock css %}
{% block title%} {{ profile.user.username }} {% endblock title%} 

{% block body%}
<br>
   <div class="container-fluid">
        <div class="row" style="text-align: right;" >

           <div class="col-2">
               <div class="side-menu" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);padding: 10px;margin: 10px;border: 5px;">
                   <div class="image-container">
                       <a href="{% url 'accounts:profile' %}">
                       <img src="{{user.profile.profile_image_url}}"  alt="" >
                       </a>
                   </div>
                   <h4 style="text-align: center;">&nbsp;{{profile.user.username}}</h4>
                   <hr>
                   <a href="{% url 'accounts:update' %}"><i class="fa fa-edit" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;بروزرسانی </a>
                   <a href="{% url 'accounts:change' %}"><i class="fa fa-key" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تغییر رمز عبور</a>
                   <a href="{% url 'accounts:history' %}"><i class="fa fa-history" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;تاریخچه</a>
                   <a href="{% url 'accounts:favourite' %}"><i class="fa fa-heart" style="font-size:20px;color: rgba(134, 138, 138, 0.877);"></i>&nbsp;علاقه مندی ها</a>
                </div>
           </div>


           <div class="col-10">
            <br>
            <h4>اطلاعات شخصی</h4>
            <div class="profile">
                <table class="table table-bordered">
                <tbody style="text-align: right;direction: rtl;">

                    <tr>                        
                        <td style="text-align: right">نام کاربری :<br> {{profile.user.username}}</td>
                        <td style="text-align: right">ایمیل :<br> {{profile.user.email}}</td>
                    </tr>

                    <tr>                    
                        <td style="text-align: right">نام :<br> {{profile.user.first_name}}</td> 
                        <td style="text-align: right">نام خانوادگی :<br> {{profile.user.last_name}}</td>                     
                    </tr>

                    <tr>                    
                        <td style="text-align: right">تلفن :<br> {{profile.phone}}</td> 
                        <td style="text-align: right">آدرس :<br> {{profile.address}}</td>                     
                    </tr>

                </tbody>
                </table>

                    <!-- <div class="card-body">    
                        <h6 class="card-subtitle mb-2 text-muted">user :{{profile.user.username}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">name :{{profile.user.first_name}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">last_name :{{profile.user.last_name}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">email :{{profile.user.email}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">phone :{{profile.phone}}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">address :{{profile.address}}</h6>
                    </div> -->
            </div>
            </div>

        </div>

        <br>
        <!-- Swiper1 -->
        <div class="row" style="text-align: right;" >
            <div class="container-fluid">
                <h3 style="text-align: right;">جدیدترین محصولات</h3>
                <hr>
                <div class="swiper-container slider1">
                <div class="swiper-wrapper">    
                    {% for j in create %}
                    <div class="swiper-slide">
                        <div class="card" style="width: 23rem;text-align: center;">
                        <img src="{{j.image_url}}" style="height: 250px;width: 250px;" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ j.name }}</h5>
                            <a href="{% url 'home:detail' j.id %}" class="btn btn-primary">مشاهده جزئیات محصول</a>
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- Add Pagination -->
                <br>
                <br>
                <div class="swiper-pagination">
                </div>
                </div>
            </div>
        </div>
        <!-- end swipper1 -->

    </div>
   <br>
   <br>
           
{% endblock body%}