accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/',views.user_register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.user_profile,name='profile'),
    path('update/',views.user_update,name='update'),
    path('change/',views.change_password,name='change'),
    path('login_phone/',views.phone,name='phone'),
    path('verify/',views.verify,name='verify'),
    path('favourite/',views.favourite,name='favourite'),
    path('history/',views.history,name='history'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns =[
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:id>/',views.add_cart,name='add_cart'),
    path('remove/<int:id>/',views.remove_cart,name='remove_cart'),
    path('add_single/<int:id>/',views.add_single,name='add_single'),
    path('remove_single/<int:id>/',views.remove_single,name='remove_single'),

]

home/urls.py
from django.urls import path, re_path
from . import views

app_name='home'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/',views.all_product,name='product'),
    path('detail/<int:id>/',views.product_detail,name='detail'),
    path('category/<slug>/<int:id>/',views.all_product,name='category'),
    path('like/<int:id>/',views.product_like,name='product_like'),
    path('unlike/<int:id>/',views.product_unlike,name='product_unlike'),
    path('comment/<int:id>/',views.product_comment,name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name='product_reply'),
    path('comment_like/<int:id>/',views.comment_like,name='comment_like'),
    # path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>/',views.favourite_product,name='favourite'),
    path('favourite_remove/<int:id>/',views.favourite_remove,name='favourite_remove'),
    path('contact/',views.contact,name='contact'),


]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/',include('order.urls', namespace='order')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'css/body.css' %}">
<html dir="rtl" lang="fa-IR" >
<head>
    
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    {% block css%}{% endblock css %}
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css" />
    <link rel='stylesheet' href='https://sachinchoolur.github.io/lightslider/dist/css/lightslider.css'>    

</head>
<body style="direction: rtl;" class="main" >
    
    {% include 'navbar.html' %}
    {% include 'message.html' %}
    {% block body%}
    {% endblock body%}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}
{% block css%}
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
{% endblock css %}

{% block body %}
<!-- Footer -->
<footer class="page-footer font-small dark-color bg-dark" style="color: cornsilk;">

  <div class="color-primary">
    <div class="container">
      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
          <!-- <div class="col-md-6 col-lg-6 text-center text-md-right mb-4 mb-md-0">
            <h6 class="mb-0" style="text-align:center;"> ارتباط با ما از طریق شبکه های اجتماعی</h6>
          </div> -->
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-12 col-lg-12 text-center text-md-left">
            <!-- Facebook -->
            <a class="fb-ic">
              <i class="fab fa-facebook-f white-text mr-4"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic">
              <i class="fab fa-twitter white-text mr-4"> </i>
            </a>
            <!-- Google +-->
            <a class="gplus-ic">
              <i class="fab fa-google-plus-g white-text mr-4"> </i>
            </a>
            <!--Linkedin -->
            <a class="li-ic">
              <i class="fab fa-linkedin-in white-text mr-4"> </i>
            </a>
            <!--Instagram-->
            <a class="ins-ic">
              <i class="fab fa-instagram white-text"> </i>
            </a>
          </div>
          <!-- Grid column -->
      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left pt-4 pt-md-5">

    <!-- Grid row -->
    <div class="row mt-1 mt-md-0 mb-4 mb-md-0">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto mt-3 mt-md-0 mb-0 mb-md-4">

        <!-- Links -->
        <h4 style="text-align: center;">فروشگاه اینترنتی ایران آمازون</h4>
        <hr class="color-primary mb-4 mt-0 d-inline-block mx-auto w-70">

        <p class="foot-desc mb-0" style="text-align: justify;" >
          فروشگاه اینترنتی ایران آمازون فعالیت خود را در زمینه پوشاک به صورت تخصصی از سال 1398 آغاز نمود
          و با تلاش‌های بی‌وقفه ضمن تنوع بخشیدن به انواع محصولات و همکاری با 
          معتبرترین برندهای دنیا (جین وست، جوتی جینز و بالنو) کیفیت اجناس خود را به میزان قابل توجهی افزایش داده که رضایت اکثریت مشتریان گرامی گواه بر این ادعاست.
        </p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto mt-3 mt-md-0 mb-0 mb-md-4">

        <!-- Links -->
        <!-- <h5>Products</h5> -->
        <hr class="color-primary mb-4 mt-0 d-inline-block mx-auto w-60">

        <ul class="list-unstyled foot-desc">
          <li class="mb-2">
            <a href="#!">
              <img style="width: 60px;height: 60px;" src="https://www.banimode.com//themes/new/assets/images/footer/samandehi.png@2x.png" alt="نشان ملی ثبت">
            </a>
          </li>
          <li class="mb-2">
            <a href="#!">
              <img style="width: 60px;height: 60px;" src="https://www.banimode.com//themes/new/assets/images/footer/logo-itehad@2x.png" alt="اتحادیه کسب و کارهای مجازی">
            </a>
          </li>
          <li class="mb-2">
            <a href="#!">
              <img style="width: 60px;height: 60px;" src="https://www.banimode.com//themes/new/assets/images/footer/eanjoman-foot.png" alt="انجمن کسب و کار اینترنتی">
            </a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <!-- <div class="col-md-3 mx-auto mt-3 mt-md-0 mb-0 mb-md-4"> -->

        <!-- Links -->
        <!-- <h5>Useful links</h5>
        <hr class="color-primary mb-4 mt-0 d-inline-block mx-auto w-60">

        <ul class="list-unstyled foot-desc">
          <li class="mb-2">
            <a href="#!">Your Account</a>
          </li>
          <li class="mb-2">
            <a href="#!">Become an Affiliate</a>
          </li>
          <li class="mb-2">
            <a href="#!">Shipping Rates</a>
          </li>
          <li class="mb-2">
            <a href="#!">Help</a>
          </li>
        </ul>

      </div> -->
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto mt-3 mt-md-0 mb-0 mb-md-4">

        <!-- Links -->
        <h5 style="text-align: center;">ارتباط با ما</h5>
        <hr class="color-primary mb-4 mt-0 d-inline-block mx-auto w-60">

        <ul class="fa-ul foot-desc ml-4" dir="rtl" style="text-align: right;">
          <li class="mb-2">تهران , خیابان ولیعصر <span class="fa-li"><i class="far fa-map"></i></span>
          </li>
          <li class="mb-2"><span class="fa-li"><i class="fas fa-phone-alt"></i></span>021 88 88 88</li>
          <li class="mb-2"><span class="fa-li"><i class="far fa-envelope"></i></span>iranamzon@gmail.com</li>
          <li><span class="fa-li"><i class="far fa-clock"></i></span>شنبه - چهارشنبه : 10-17</li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">©  2021 تمامی حقوق متعلق به خرید اینترنتی | فروشگاه آنلاین (شرکت توسعه تجارت الکترونیک ایران آمازون) می‌باشد .
    <!-- <a href="https://mdbootstrap.com/"> MDBootstrap.com</a> -->
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

{% endblock %}

<style> 
  .newspaper {
    column-count: 3;
  }
  
</style>

templates/message.html
{% if messages %}
    {% for msg in messages %}
        <h4 {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif %}>{{msg}}</h4>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/nav.css' %}">
{% endblock css %}
<!--Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="height: 100px;" >
    <div class="collapse navbar-collapse" id="navbarSupportedContent-555">

      <div class="navbar-nav mr-auto" dir="rtl">
          <a class="nav-link" href="{% url 'home:home' %}">
            <img src="/media/logo/logo.png" class="rounded-circle z-depth-0"
              alt="" style="width: 60px;height:60px"> 
            <span class="sr-only">(current)</span>
          </a>
          &emsp;
          
        <form class="form-inline float-sm-right" action="{% url 'home:product' %}">
          {% csrf_token %}
          <input class="form-control" style="width: 500px; height: 60px; border-radius: 7px;" type="search" placeholder="&#128269;&nbsp; جستجو..." name="search">
          <input type="submit" style="visibility: hidden; position: absolute;" />
            <!-- <i class="fas fa-search" style="color: rgb(12, 12, 12);"></i> -->        
        </form>
        
         <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'home:product' %}">Products</a>
         </li>

        <!-- this section for nested dropdown if we want show on navbar -->
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-55" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: cornsilk;">
              Category
          </a>
          <div class="dropdown-menu dropdown-secondary" aria-labelledby="navbarDropdownMenuLink-555">
            <ul>
              {% for cat in category %}
                <li>
                  <a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a>
                  <div class="dropdown-menu">
                    <ul>
                      {% for info in cat.sub.all %}
                        <li>
                          <a class="dropdown-item hover:blue" href="{{info.get_absolute_url}}">{{info.name}}</a>
                        </li> 
                      {% endfor %}
                    </ul>
                  </div>
                </li>
              {% endfor %}
            </ul>
          </div>
        </li> -->
      </div>

      <div class="container" style="justify-content: left;" dir="ltr">
        {% if user.is_authenticated %}
          <a class="nav-link waves-effect waves-light" href="{% url 'cart:cart_detail' %}">             
            <i class="fas fa-shopping-basket" style="font-size: 25px;color: blanchedalmond;" ><span class='badge badge-primary' id='lblCartCount' style="font-size: 20px;"> {{nums}} </span>
            </i>
          </a>
        {% else %} 
          <a class="nav-link waves-effect waves-light">
            <i class="fas fa-shopping-basket" style="font-size: 25px;color: blanchedalmond;"></i>
          </a>
        {% endif %}

        <!-- vertical line for seprate basket and user profile -->
        <div style=" border-left: 3px solid rgba(160, 159, 159, 0.466);height: 50px;margin-left: 10px;top: 12px;">
        </div>
        <!-- end for vertical line -->
          
        <div class="nav-item avatar dropdown" >
          <a class="nav-link" id="navbarDropdownMenuLink-55" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="color: cornsilk;">
            <i class="fa fa-angle-down" style="margin-top: 20px;"></i>
            &ensp;
            {% if user.is_authenticated %}
              <img src="{{user.profile.profile_image_url}}" class="rounded-circle z-depth-0"
              alt="" style="width: 30px;height:30px">                            
            {% else %}
 
              <img src="/media/profile/1.jpg" class="rounded-circle z-depth-0"
              alt="" style="width: 30px;height:30px" style="color: cornsilk;">&ensp;                           
            {% endif %}
          </a>

          <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"
              aria-labelledby="navbarDropdownMenuLink-55" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);text-align: right;" dir="rtl">
            {% if user.is_authenticated %}
              <h5 style="text-align: center;">{{user.username}}</h5>
              <hr>              
              <a class="dropdown-item" href="{% url 'accounts:profile' %}">مشاهده پروفایل</a>              
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">خروج</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'accounts:register' %}"> ثبت نام </a>
              <!-- <a class="dropdown-item" href="" data-toggle="modal" data-target="#modelslogin">log in </a> -->
              <a class="dropdown-item" href="{% url 'accounts:login' %}" >  ورود به حساب کاربری</a>
            {% endif %}
          </div>
        </div>

      </div>        
    </div>

  <!-- this section has for if we want use modals for login or register action -->
  <!-- modals login -->
  <!-- <div class="modal" tabindex="-1" role="dialog" id="modelslogin" >
    <div class="modal-dialog" ;>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" style="padding-left: 10em;">login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token%}
            <div class="form-group">
                <input type="text" name="user" class="form-control" placeholder="Your username *" value="" />
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Your Password *" value="" />
            </div>
            <div class="form-group" style="padding-left: 10em;">
              <input type="submit" class="btnSubmit"  value="Login" />
            </div>
            <div class="form-group">
                <label for="default-remember">
                <input type="checkbox" id="default-remember" /> Remember me</label>
                <a href="" class="ForgetPwd" style="padding-left: 12em;" value="Login" data-dismiss="modal" data-toggle="modal" data-target="#modelsphone">&nbsp;Forget Password?</a>
            </div>
          </form>
              -->
  
        <!-- </div> -->
        <!-- <div class="modal-footer"> -->
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
          <!-- <a href="{% url 'accounts:login' %}" class="btn btn-success">log in</a> -->
        <!-- </div> -->
      <!-- </div>
    </div>
  </div> -->

  </nav>

<style>
ul {
  list-style-type: none;
}
.modal{
  padding: 5%;
  box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
}
.btnSubmit
{
    width: 50%;
    border-radius: 1rem;
    padding: 1.5%;
    border: none;
    cursor: pointer;
}
.form-group .btnSubmit{
  font-weight: 600;
  color: #fff;
  background-color: #0062cc;
}
.container {
  display: flex;
  justify-content: center;
  align-items: center;
}
.dropdown-item {
  text-decoration: none;
  color: black;

}
.dropdown-item .hover {
  text-decoration: underline;
  color: #0062cc;

}



/* .dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 12px 16px;
  z-index: 1;
}

.dropdown:hover .dropdown-content {
  display: block;
} */

.badge {
  padding-left: 9px;
  padding-right: 9px;
  -webkit-border-radius: 9px;
  -moz-border-radius: 9px;
  border-radius: 9px;
}

.label-warning[href],
.badge-warning[href] {
  background-color: #c67605;
}
#lblCartCount {
    font-size: 12px;
    background: #ff0000;
    color: #fff;
    padding: 0 5px;
    vertical-align: top;
    margin-left: -10px; 
}
</style>